export const item=[
    {
        name:"任务管理",
        imgSrc:require("imgPath/kanban.png"),
        child:[
            "数据看板",
            "新增项目"
        ],
        isActive:true
    },
    {
        name:"人才简历",
        imgSrc:require('imgPath/talent.png'),
        child:[
            "数据看板",
            "人才简历"
        ],
        isActive:false
    },
    {
        name:"人才管家",
        imgSrc:require("imgPath/talenthub.png"),
        child:[
            "上传简历"
        ],
        isActive:false
    },
    {
        name:"我的团队",
        imgSrc:require("imgPath/team.png"),
        child:[],
        isActive:false
    },
    {
        name:"个人中心",
        imgSrc:require("imgPath/personal.png"),
        child:[],
        isActive:false
    }
];