export const item=[
    {
        name:"任务管理",
        imgSrc:require("imgPath/kanban.png"),
        imgAct:require("imgPath/kanbanactive.png"),
        child:[
            "数据看板",
            "新增项目"
        ],
        link:"TaskManagement",
        isActive:true,
        index:0
    },
    {
        name:"人才简历",
        imgSrc:require('imgPath/talent.png'),
        imgAct:require("imgPath/talentactive.png"),
        child:[],
        link:"Talent",
        isActive:false,
        index:1
    },
    {
        name:"人才管家",
        imgSrc:require("imgPath/talenthub.png"),
        imgAct:require("imgPath/talenthubactive.png"),
        child:[
            "上传简历"
        ],
        link:"Talenthub",
        isActive:false,
        index:2
    },
    {
        name:"我的团队",
        imgSrc:require("imgPath/team.png"),
        imgAct:require("imgPath/teamactive.png"),
        child:[],
        link:"Myteam",
        isActive:false,
        index:3
    },
    {
        name:"个人中心",
        imgSrc:require("imgPath/personal.png"),
        imgAct:require("imgPath/personalactive.png"),
        child:[],
        link:"Personal",
        isActive:false,
        index:4
    }
];